_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [ ]:
import numpy as np

# Create the array
arr = np.array([10, 5, 7, 20, 15, -9, 33])

# Print the array
print("Array:", arr)

# Find the maximum and minimum values
max_value = np.max(arr)
min_value = np.min(arr)

# Print the maximum and minimum values
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Array: [10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [ ]:
import numpy as np

def find_max(arr):
    if len(arr) == 0:
        return None

    max_value = arr[0]  # Assume the first element is the maximum

    for element in arr[1:]:
        if element > max_value:
            max_value = element

    return max_value

# Accepting array of elements from the user
arr = np.array(input("Enter elements of the array separated by spaces: ").split(), dtype=int)

# Finding the maximum value
max_value = find_max(arr)

if max_value is not None:
    print("Maximum value:", max_value)
else:
    print("Array is empty")

Enter elements of the array separated by spaces: 1 2 5 3 23 56 7
Maximum value: 56


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [ ]:
import numpy as np

# Define the matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 4], [6, 8]])

# Find the sum of matrices
sum_result = matrix1 + matrix2
print("Sum of the matrices:")
print(sum_result)

# Find the subtraction of matrices
subtraction_result = matrix1 - matrix2
print("\nSubtraction of the matrices:")
print(subtraction_result)


Sum of the matrices:
[[ 3  6]
 [ 9 12]]

Subtraction of the matrices:
[[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [ ]:
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.rand(5, 6)
print("Random Matrix:")
print(random_matrix)

# Add another row with random elements
new_row = np.random.rand(1, 6)
random_matrix = np.vstack([random_matrix, new_row])
print("\nMatrix with added row:")
print(random_matrix)

# Find the sum of each row
row_sums = np.sum(random_matrix, axis=1)
print("\nSum of each row:")
print(row_sums)

Random Matrix:
[[0.00462922 0.59256579 0.79116505 0.10772963 0.89812273 0.75566439]
 [0.82476347 0.76788912 0.12009982 0.69803707 0.93452727 0.46269139]
 [0.50062732 0.64076956 0.87789721 0.73250293 0.58820594 0.46491282]
 [0.68015672 0.9341167  0.81987803 0.8657766  0.11426552 0.24360998]
 [0.90195451 0.19173367 0.08944803 0.33335856 0.90809886 0.25166881]]

Matrix with added row:
[[0.00462922 0.59256579 0.79116505 0.10772963 0.89812273 0.75566439]
 [0.82476347 0.76788912 0.12009982 0.69803707 0.93452727 0.46269139]
 [0.50062732 0.64076956 0.87789721 0.73250293 0.58820594 0.46491282]
 [0.68015672 0.9341167  0.81987803 0.8657766  0.11426552 0.24360998]
 [0.90195451 0.19173367 0.08944803 0.33335856 0.90809886 0.25166881]
 [0.23062403 0.70994096 0.78761183 0.81775131 0.8359904  0.78778329]]

Sum of each row:
[3.14987682 3.80800815 3.80491578 3.65780354 2.67626245 4.16970183]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [ ]:
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.randint(0, 10, size=(5, 6))
print("Random Matrix:")
print(random_matrix)

# Add another column with random elements
new_column = np.random.randint(0, 10, size=(5, 1))
random_matrix = np.hstack([random_matrix, new_column])
print("\nMatrix with added column:")
print(random_matrix)

# Compute the sine of each element
sin_matrix = np.sin(random_matrix)
print("\nSine of each element:")
print(sin_matrix)

Random Matrix:
[[9 3 9 4 7 7]
 [1 6 5 4 5 4]
 [6 8 4 5 3 7]
 [7 6 7 9 1 7]
 [0 1 5 6 9 1]]

Matrix with added column:
[[9 3 9 4 7 7 5]
 [1 6 5 4 5 4 9]
 [6 8 4 5 3 7 0]
 [7 6 7 9 1 7 6]
 [0 1 5 6 9 1 8]]

Sine of each element:
[[ 0.41211849  0.14112001  0.41211849 -0.7568025   0.6569866   0.6569866
  -0.95892427]
 [ 0.84147098 -0.2794155  -0.95892427 -0.7568025  -0.95892427 -0.7568025
   0.41211849]
 [-0.2794155   0.98935825 -0.7568025  -0.95892427  0.14112001  0.6569866
   0.        ]
 [ 0.6569866  -0.2794155   0.6569866   0.41211849  0.84147098  0.6569866
  -0.2794155 ]
 [ 0.          0.84147098 -0.95892427 -0.2794155   0.41211849  0.84147098
   0.98935825]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [ ]:
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.randint(0, 10, size=(5, 6))
print("Random Matrix:")
print(random_matrix)

# Extract the specified rows and columns using slicing
resultant_matrix = random_matrix[2:4, 1:4]
print("\nResultant Matrix:")
print(resultant_matrix)

Random Matrix:
[[8 5 8 3 6 9]
 [9 5 9 3 0 3]
 [6 7 8 1 4 3]
 [0 0 7 6 3 7]
 [6 7 6 8 8 5]]

Resultant Matrix:
[[7 8 1]
 [0 7 6]]


### Great Job!